#!/bin/zsh

RED='\033[0;31m'
BOLD=$(tput bold)
NORM=$(tput sgr0)


# copy dotfiles (replace with git clone --bare)
# source .zshrc
echo "\n${RED}${BOLD}(1/6)${NORM} copying dotfiles\n"
source ~/.zshrc
source ~/.zshenv
source ~/.vimrc
echo "${RED}${BOLD}(1/6)${NORM} ...done\n"

# Install rosetta on Apple Silicon if not installed
if [[ $(arch) == 'arm64' && -z $(pkgutil --pkgs | grep Rosetta) ]]
then
    echo "\n${RED}${BOLD}(1.5/6)${NORM} Installing rosetta2\n"
    softwareupdate --install-rosetta
    echo "\n${RED}${BOLD}(1.5/6)${NORM} ...done\n"
fi

# Install Homebrew
echo "\n${RED}${BOLD}(2/6)${NORM} Installing Homebrew\n"
if brew -h 1>/dev/null
then
    echo "Brew already installed."
else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "${RED}${BOLD}(2/6)${NORM} ...done\n"

# Install formulas
echo "\n${RED}${BOLD}(3/6)${NORM} Installing formulas\n"
brew install \
    wget \
    htop \
    macvim \
    tmux \
    coreutils \
    socat \
pip3 install --user powerline-status
echo "\n${RED}${BOLD}(3/6)${NORM} ...done\n"


# Install casks
echo "\n${RED}${BOLD}(4/6)${NORM} Installing casks\n"
brew install --cask \
    owncloud \
    vlc \
    dropbox \
    google-chrome \
    focus \
    zoom \
    iriunwebcam \
    spotify \
    sound-control \
    lulu \
    iterm2 \
    anki \
    netnewswire \
    anydesk \
    fanny \
    calibre \
    rectangle \
    tunnelblick \
    hex-fiend \
    burp-suite \
    local \
    cutter \
    gimp \
    transmission \
    nordvpn \
    appcleaner \
    mactex-no-gui \
    tex-live-utility \
    texstudio \
    the-unarchiver \
    mattermost \ 
    blurred \
    hiddenbar
echo "\n${RED}${BOLD}(4/6)${NORM} ...done\n"


# Get further apps for manual installation (meeter, xournal++)
echo "\n${RED}${BOLD}(5/6)${NORM} Downloading further apps\n"
wget -i downloads.txt
echo "\n${RED}${BOLD}(5/6)${NORM} ...done\n"

## Doesnt work with Apple Silicon ?
# brew install --cask adoptopenjdk ghidra


# Install vim-plug
echo "\n${RED}${BOLD}(6/6)${NORM} Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "\n${RED}${BOLD}(6/6)${NORM} ...done\n"

# what's next?
echo "\n${RED}${BOLD}Next:${NORM} Install xournal++, meeter, oh-my-zsh?\n"

echo "Don't forget the ssh-keys and run PlugInstall!"
